# Generated by Django 5.1.6 on 2026-04-05 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roomm_host_roomm_topic_delete_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomm',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='roomm',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
